apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-auth-config
data:
  PORT: "6000"
  LOG_LEVEL: "info"
  LOG_DIR: "logs"
  DB_NAME: "auth"
  DB_HOST: "mongo-auth-srv"
  DB_PORT: "27017"
  DB_MIN_POOL_SIZE: "5"
  DB_MAX_POOL_SIZE: "10"
  SALT_ROUNDS: "10"
  JWT_EXPIRES_IN: "15m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-auth
  template:
    metadata:
      labels:
        app: ticketing-auth
    spec:
      containers:
        - name: ticketing-auth
          image: ajayjb/ticketing-auth:latest
          envFrom:
            - configMapRef:
                name: ticketing-auth-config
          env:
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: ENVIRONMENT
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: JWT_KEY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ticketing-auth-secret
                  key: DB_USER
            - name: DB_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: ticketing-auth-secret
                  key: DB_USER_PWD

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-auth-srv
spec:
  type: ClusterIP
  selector:
    app: ticketing-auth
  ports:
    - name: ticketing-auth-srv-port
      protocol: TCP
      port: 6000
      targetPort: 6000
