apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-client
  template:
    metadata:
      labels:
        app: ticketing-client
    spec:
      containers:
        - name: ticketing-client
          image: ajayjb/ticketing-client:latest
          env:
            - name: NEXT_PUBLIC_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: ENVIRONMENT
            - name: NEXT_PUBLIC_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: ticketing-client-secret
                  key: NEXT_PUBLIC_DOMAIN
            - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-client-srv
spec:
  type: ClusterIP
  selector:
    app: ticketing-client
  ports:
    - name: ticketing-client-srv-port
      protocol: TCP
      port: 3000
      targetPort: 3000
