apiVersion: v1
kind: ConfigMap
metadata:
  name: expiration-service-config
data:
  LOG_LEVEL: "info"
  LOG_DIR: "logs"
  REDIS_HOST: "expiration-redis-srv"
  REDIS_PORT: "6379"
  NATS_CLUSTER_ID: "tickets"
  NATS_URL: "nats://nats-srv:4222"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-service
  template:
    metadata:
      labels:
        app: expiration-service
    spec:
      containers:
        - name: expiration-service
          image: ajayjb/expiration-service:latest
          envFrom:
            - configMapRef:
                name: expiration-service-config
          env:
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: ENVIRONMENT
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name