
name: tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: payments/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: payments

      - name: Run tests
        run: yarn test:ci
        working-directory: payments
        env:
          PORT: "6000"
          ENVIRONMENT: "test"
          LOG_LEVEL: "info"
          LOG_DIR: "logs"
          VERSION: "v1"
          DB_NAME: "test"
          DB_HOST: "localhost"
          DB_PORT: "27017"
          DB_USER: "test_user"
          DB_USER_PWD: "test_password_123"
          DB_MIN_POOL_SIZE: "5"
          DB_MAX_POOL_SIZE: "10"
          SALT_ROUNDS: "10"
          JWT_KEY: "test_jwt_key_dummy_secret_12345"
          NATS_CLUSTER_ID: "tickets"
          NATS_URL: "nats://localhost:4222"
          NATS_CLIENT_ID: "3"
